MyChat/Models/Message.cs
namespace MyChat.Models;

public class Message
{
    public int Id { get; set; }
    public string Body { get; set; }
    public DateTime Created { get; set; } = DateTime.UtcNow;

    public int UserId { get; set; }
    public User User { get; set; }
}

MyChat/Controllers/MessageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyChat.Models;

namespace MyChat.Controllers;

[Authorize]
public class MessageController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly MyChatContext _context;
    public MessageController(UserManager<User> userManager, MyChatContext context)
    {
        _context = context;
        _userManager = userManager;
    }
    [ResponseCache(CacheProfileName = "NoCaching")]
    public IActionResult Chat()
    {
        return View();
    }
    [HttpGet]
    [ResponseCache(CacheProfileName = "NoCaching")]
    public async Task<IActionResult> GetMessages()
    {
        var messages = await _context.Messages.Include(m => m.User).OrderByDescending(m => m.Created).Take(30).ToListAsync();
        return PartialView("_MessagesPartial", messages);
    }
    [ResponseCache(CacheProfileName = "NoCaching")]
    public async Task<IActionResult> CreateAjax(string? username, string? body)
    {
        if (username != null && body != null)
        {
            User user = await _userManager.FindByNameAsync(username);
            if (user != null)
            {
                Message msg = new()
                {
                    UserId = user.Id,
                    Body = body
                };
                await _context.AddAsync(msg);
                await _context.SaveChangesAsync();
                return Json(new { success = true });
            }
        }
        return Json(new { success = false });
    }
}

MyChat/Views/Message/Chat.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer loc;
@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/css/chat.css"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js" />


<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card card-bordered">
                    <div class="card-header">
                        <h4 class="card-title"><strong>Chat</strong></h4>
                        <a class="btn btn-xs btn-secondary" href="#" data-abc="true">Let's Chat App</a>
                    </div>


                    <div class="ps-container ps-theme-default ps-active-y" id="chat-content" style="overflow-y: scroll !important; height:400px !important;">
                        <div id="messages">

                        </div>
                        @* Сообщения *@
                        <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; height: 0px; right: 2px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 2px;"></div></div>
                    </div>

                    <div class="publisher bt-1 border-light">
                        <input id="body" maxlength="100" class="publisher-input" type="text" placeholder="@loc["Write"]">
                        <button id="submit" onclick="sendMessage('@User.Identity.Name')" type="submit">@loc["Send"]</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
        crossorigin="anonymous">
</script>

<script>
    $('body').on('input', 'input[type="text"][maxlength]', function () {
        if (this.value.length > this.maxlength) {
            this.value = this.value.slice(0, this.maxlength);
        }
    })
    function sendMessage(username) {
        event.preventDefault();
        $.ajax({
            url: '@Url.Action("CreateAjax", "Message")',
            type: 'POST',
            data: { 'username': username, 'body': $('#body').val() },
            success: console.log('good'),
            error: console.log('error'),
        });
        return false;
    }

    function loadMessages() {
        $.ajax({
            url: '@Url.Action("GetMessages", "Message")',
            type: 'GET',
            success: function (data) {
                $('#messages').html(data);
                console.log('GOOD');
            },
        });
    }
    loadMessages();

    setInterval(loadMessages, 5000);

    
</script>

MyChat/Views/Message/_MessagesPartial.cshtml
@model List<Message>

@foreach (var msg in Model)
{
    @if (msg.User.UserName == User.Identity.Name)
    {
        @* Мои сообщения *@
        <div class="media media-chat media-chat-reverse">
            <img class="avatar" src="@msg.User.Avatar" alt="...">
            <div class="media-body">
                <p>@msg.Body</p>
                <p class="meta"><a asp-action="Details" asp-controller="User" asp-route-name="@msg.User.UserName">@msg.User.UserName</a></p>
                <p class="meta text-dark"><time datetime="2018">@msg.Created.ToLongTimeString()</time></p>
            </div>
        </div>
    }
    else
    {
        @* Чужие сообщения *@
        <div class="media media-chat">
            <img class="avatar" src="@msg.User.Avatar" alt="...">
            <div class="media-body">
                <p>@msg.Body</p>
                <p class="meta"><a asp-action="Details" asp-controller="User" asp-route-name="@msg.User.UserName">@msg.User.UserName</a></p>
                <p class="meta"><time datetime="2018">@msg.Created.ToLongTimeString()</time></p>
            </div>
        </div>
    }
}